apiVersion: v1
kind: Service
metadata:
  name: {{ include "agent.fullname" . }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.agent.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "agent.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.agent.service.port }}
      targetPort: http
