apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vinculum.infra.name" . }}
  labels:
    helm.sh/chart: {{ include "vinculum.chart" . }}
    app.kubernetes.io/name: {{ include "vinculum.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  KEYCLOAK_ADMIN_USERNAME: {{ .Values.vinculumInfra.secrets.keycloakAdminUsername | quote }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.vinculumInfra.secrets.keycloakAdminPassword | quote }}
  FORGEJO_ADMIN_USERNAME: {{ .Values.vinculumInfra.secrets.forgejoAdminUsername | quote }}
  FORGEJO_ADMIN_PASSWORD: {{ .Values.vinculumInfra.secrets.forgejoAdminPassword | quote }}
